use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let mut entries = Vec::new();
    find_command_files(Path::new("src/commands"), &mut entries);

    // Ignore mod.rs files and hidden files
    let mut modules = Vec::new();
    let mut commands = Vec::new();
    for file in &entries {
        let fname = file.file_name().unwrap().to_string_lossy();
        if fname == "mod.rs" || fname.starts_with('.') {
            continue;
        }
        // src/commands/foo/bar.rs --> foo::bar
        let rel_path = file.strip_prefix("src/commands").unwrap();
        let modpath = rel_path.with_extension(""); // strip .rs
        let module_path = modpath
            .components()
            .map(|c| c.as_os_str().to_string_lossy())
            .collect::<Vec<_>>();
        let funcname = module_path.last().unwrap().to_string();
        let modpath_for_use = format!("crate::commands::{}", module_path.join("::"));
        if module_path.len() > 1 {
            modules.push(module_path[..module_path.len() - 1].join("::"));
        }
        commands.push((modpath_for_use, funcname));
    }

    modules.sort();
    modules.dedup();

    // --- Generate src/commands/mod.rs ---
    barexp::build();
    // --- End: mod.rs generation ---

    // Generate commands_gen.rs
    let out_path = Path::new("src/commands_gen.rs");
    let mut file = fs::File::create(out_path).expect("Could not create src/commands_gen.rs");
    writeln!(file, "// This file is auto-generated by build.rs").unwrap();

    writeln!(
        file,
        "pub fn all_commands() -> Vec<poise::Command<crate::Data, crate::Error>> {{"
    )
    .unwrap();
    writeln!(file, "    vec![").unwrap();
    for (modpath, funcname) in &commands {
        writeln!(file, "        {}::{funcname}(),", modpath).unwrap();
    }
    writeln!(file, "    ]").unwrap();
    writeln!(file, "}}").unwrap();
}

fn find_command_files(dir: &Path, files: &mut Vec<PathBuf>) {
    if dir.is_dir() {
        for entry in fs::read_dir(dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            if path.is_dir() {
                find_command_files(&path, files);
            } else if path.extension().map(|e| e == "rs").unwrap_or(false) {
                files.push(path);
            }
        }
    }
}
