version: "3.8" # Specify the version for compatibility

services:
    agentkitten:
        build:
            context: ./ # Use the current directory as the build context
            dockerfile: ./Dockerfile # Correct path to your Dockerfile
        env_file:
            - ./.env
