services:
    agentkitten:
        build:
            context: ./ # Use the current directory as the build context
            dockerfile: ./Dockerfile # Correct path to your Dockerfile
        env_file:
            - ./.env
    browser:
        image: ghcr.io/browserless/chromium:latest
        ports:
          - 3000:3000
