// This file is auto-generated by build.rs
pub fn all_commands() -> Vec<poise::Command<crate::Data, crate::Error>> {
    vec![
        crate::commands::leveling::level::level(),
        crate::commands::leveling::leaderboard::leaderboard(),
        crate::commands::config::userconf::userconf(),
        crate::commands::config::serverconf::serverconf(),
        crate::commands::music::clear::clear(),
        crate::commands::music::seek::seek(),
        crate::commands::music::swap::swap(),
        crate::commands::music::remove::remove(),
        crate::commands::music::join::join(),
        crate::commands::music::pause::pause(),
        crate::commands::music::play::play(),
        crate::commands::music::resume::resume(),
        crate::commands::music::queue::queue(),
        crate::commands::music::stop::stop(),
        crate::commands::music::leave::leave(),
        crate::commands::music::skip::skip(),
        crate::commands::utils::help::help(),
        crate::commands::utils::debug::debug(),
        crate::commands::textgen::chat::chat(),
        crate::commands::textgen::chatreset::chatreset(),
    ]
}
