name: Linton

on:
    pull_request: null

permissions: {}

jobs:
    build:
        name: Lint
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
            statuses: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Node.js LTS 20
              uses: actions/setup-node@v3
              with:
                  node-version: "20" # Specify LTS version 20

            - name: Install npm dependencies
              run: npm install # Ensure you have a package.json with required dependencies

            - name: Run Prettier to fix lint issues
              run: |
                  npx prettier --check . 
                  npx prettier --write .

            - name: Run ESLint to fix lint issues
              run: npx eslint . --fix
